### ISSUE TITLE
SGB MLT_REQ

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#242] opened 2019-12-17 16:36 UTC
The SGB MLT_REQ command is incorrectly implemented.  This was fixed in upstream bsnes some time around v107 or v108, but there have been a few updates since then.  Most of the relevant changes seem to be here: https://github.com/byuu/bsnes/blob/master/bsnes/sfc/coprocessor/icd/interface.cpp

Which should go here:
https://github.com/devinacker/bsnes-plus/blob/master/supergameboy/interface/interface.cpp

Unfortunately, due to the way upstream commits were done as large snapshots up until recently, it's hard to pin down the exact changes, and is probably easiest to just diff the two in their current state.

**Comment by qwertymodo** [comment] 2019-12-17 16:40
The most obvious example I can think of to demonstrate the issue is Pokemon Yellow, which should have a custom border on the SGB, but doesn't due to the failed SGB detection via MLT_REQ.

**Comment by Conn79** [comment] 2019-12-17 20:45
The reason qwerty is asking, is that I would like to add msu1 support for the favorite game of my youth, Final Fantasy adventure.

The asm for the gb rom is relatively simple, I can mute it by 
ROM0: 119C E0 90 ld (FF00+90),a
(this writes the track theme to HRAM FF90, so nop out will result in a mute)
ROM0: 119E EA 9B D4 ld (D49B),a
(this writes the track number into WRA1 D49B

So, if I have the track number, I could very simply modify the SGB bios ram to run a msu code. The problem is: how do I get the byte at GB D49B to an arbitrary snes sgb ram?

I found that the gb header is transferred by 
00bc11 lda $7000,y   [017000] A:e500 X:0000 Y:0000 
00bc14 sta $0600,x   [010600] A:e5f1 X:0000 Y:0000 
into snes ram (this reads gb rom data 0104-014f and transfers it into snes ram 0600-0650 region). But I have no idea how to modify the $7000 (if possible) to read from the offset D49B.

Qwertymodo asks for MLT_REQ because we want to try the DATA_SND respectively DATA_TRN method, but I do not know whether it may work since it may only be able to send fixed value bytes (not from dynamical changing GB wram).

Has anybody here maybe a solution how to archieve this goal? All is needed to transfer one byte from GB wram into snes wram...

**Comment by devinacker** [comment] 2019-12-17 21:44
Thanks, I'll take a look after work and see what's up.

**Comment by Conn79** [comment] 2019-12-18 16:10
Just a small update, adding msu1 to sgb bios seems to be not possible (so please forget about my post):
https://helmet.kafuka.org/bboard/thread.php?pid=5217#5217

**Comment by devinacker** [comment] 2019-12-18 19:30
Okay, it just looks like a small change in how the index of the current joypad being polled changes under some circumstances. I can make the change pretty quickly when I get home from work and test it with Pokemon Yellow and see what happens

**Comment by devinacker** [comment] 2019-12-18 23:45
Try it now, Pokemon Yellow and Killer Instinct both seem ok. Haven't tested anything else with the change yet.

**Closed** 2019-12-24 02:14 UTC
Labels: bug
