### ISSUE TITLE
Ignore input when main window does not have focus - OPTION NOT WORKING!!

### ISSUE THREAD

**Issue by PeladoFeo** [devinacker/bsnes-plus#109] opened 2017-02-16 22:19 UTC
Title explains it all.

**Comment by devinacker** [comment] 2017-02-16 23:58
It works fine for me, and presumably also most people. What OS and emulator version are you using?

**Comment by PeladoFeo** [comment] 2017-02-17 01:46
I'm using the latest release of bsnes+ on Windows 7.

**Comment by devinacker** [comment] 2017-02-17 18:38
Does this happen when focus is on a different bsnes-plus window other than the main window, or when focus is on a different application entirely, or both? I'm still not able to reproduce the issue either way.

**Comment by PeladoFeo** [comment] 2017-02-17 21:13
Actually the bug happens in fullscreen mode.

**Comment by devinacker** [comment] 2017-02-19 02:25
I still don't have a problem in fullscreen mode, sorry.

What exactly do you mean by "not working"? Does the emulator not accept input when the window has focus, or does it incorrectly accept input when the window doesn't have focus? There's really not enough information here for me to determine what the problem might be.

**Comment by mrehkopf** [comment] 2017-02-19 07:51
How can the main window even be out of focus in fullscreen mode? The only situation I can think of is a multi-display setup.

**Comment by devinacker** [comment] 2017-02-19 08:08
It's not "true" fullscreen, so you can alt-tab etc. and get a different window in focus with the main window still fullscreen behind it.

As far as I can tell, though, that doesn't cause any problems with ignoring input on my end.

**Comment by mrehkopf** [comment] 2017-02-19 19:20
I see. Works for me too. I wonder if some registry settings to tweak mouse focus behaviour might interfere with it.

**Comment by devinacker** [comment] 2018-09-20 16:07
closing due to lack of input, if you're still having the same issue with the most recent release then please reply with more information

**Closed by devinacker** 2018-09-20 16:07 UTC
Labels: unable to reproduce
