### ISSUE TITLE
Memory Editor Window Issues

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#228] opened 2019-08-30 19:52 UTC
There are a handful of issues with the Memory Editor Window.  If you try to open it more than once, it opens multiple windows instead of bringing the existing one into focus.  Also if you reload the game with the Memory Window open, it stops working and no longer updates with the reloaded data (also happens when loading a new game).  There were a couple of other oddities, but I can't remember them off the top of my head.  They're likely all due to a common root cause, since the window no longer seems to follow the same one-window-instance-per-app-instance behavior as the other windows like the debugger, breakpoint editor, cheats editor, etc.

**Comment by devinacker** [comment] 2019-08-31 00:16
>If you try to open it more than once, it opens multiple windows instead of bringing the existing one into focus
That was actually a deliberate change that I merged as part of the newdebugger branch - see 6f1751fa8ac541d1897c694c42f49779aa104807

I might add an option to restore the old behavior, though.

The rest may indeed be related regressions though, I'll check it out soon.

**Comment by qwertymodo** [comment] 2019-08-31 02:49
I actually like the ability to have multiple windows open, so no need to remove that as long as those windows can continue to work when the game is reloaded.

**Comment by devinacker** [comment] 2019-08-31 03:36
Hmm, I don't seem to have any problems refreshing the memory viewers - I can open something like 4 or 5 of them at once and as long as they all have "auto update enabled", they'll continue updating properly both when reloading the same ROM or loading a different one. Is there something I should be doing differently?

**Comment by qwertymodo** [comment] 2019-09-02 07:19
Ok, I'll mess around with it some more and see if I can isolate specific repro steps, or whether I'm just failing at using it.

**Comment by randomdude999** [comment] 2019-12-01 13:03
I could reproduce this in v05, but it seems to be fixed in master.

**Closed** 2020-07-02 17:25 UTC
Labels: bug, ui, unable to reproduce
