### ISSUE TITLE
Requests for Memory Editor

### ISSUE THREAD

**Issue by therealinfidelity** [devinacker/bsnes-plus#162] opened 2018-02-10 18:32 UTC
Id still like to know if these features will be implemented into bsnes-plus? They are all for the Memory Editor.

1: When viewing the Cartridge ROM, can the "Refresh" button please refresh the already logged code? Because this way, I can see what is currently being ran as code/data. Because as it is now, the Cartridge ROM does not allow a refresh of all the hex that are colored. So I'm unable to determine what is specifically/continuously being called/ran.

2: When manually editing the values, can the edited color be something that stands out, like a sharp red color? Because as it is now, the values you type within the hex Memory Editor, its color matches the same color you are editing. So you have no guide as to what you have edited.

3: If #2 gets implemented, restore original color of previously edited hex value when erasing edited hex value(s).

Thank you!

**Comment by devinacker** [comment] 2018-02-23 01:27
Closing since this is basically a duplicate of #75, but also:

I'm mostly holding off on revisiting UI stuff until I start merging [Benny's new debugger frontend](http://forums.nesdev.com/viewtopic.php?f=12&t=16625) after the upcoming v4 release. (I originally wanted to look into it as part of said release, but it's been so long since the last one and with so much other stuff I need to get out there that I kind of changed plans a bit)

**Closed by devinacker** 2018-02-23 01:27 UTC
