### ISSUE TITLE
MSU-1 Resume

### ISSUE THREAD

**Issue by qwertymodo** [devinacker/bsnes-plus#64] opened 2016-10-20 00:09 UTC
Looking at the MSU-1 code, it doesn't look like you currently support the resume flag ($2007=$04).  Resume support should also increase the MSU-1 version flag to revision 2.

**Comment by devinacker** [comment] 2016-10-20 01:15
This is something I've been meaning to add ever since the draft version of it was added to someone's fork of bsnes-plus a while ago. I think my lack of MSU-1 test ROMs has made me put it off, but I planned to add it and also fix #54 at the same time.

**Comment by devinacker** [comment] 2016-10-21 00:56
Finally added resume support in 3908d5ef94578394a93ceb911b879747b44555a9, haven't tested it.

There are some small discrepancies I noticed between bsnes-plus and higan now, such as how bsnes-plus clears some flags when writing to $2005 but higan seemingly doesn't, but I'm not sure if that's really important.

**Comment by qwertymodo** [comment] 2016-10-21 01:00
Which flags?  It might be worth asking byuu for a definitive clarification to avoid divergence, or at the very least ambiguity.  Maybe they don't affect anything functionally, but they might.

**Comment by devinacker** [comment] 2016-10-21 01:07
audio_busy, audio_resume and audio_play are all cleared when writing to $2005. The former probably doesn't matter since it is almost always false (and in higan it *is* always false, from what I can see).

**Comment by qwertymodo** [comment] 2016-10-21 01:12
audio_busy should be set during the period of time when you're determining whether or not the track exists, then cleared once the track_missing flag is definitively set or cleared.  That one does matter because it's readable.  audio_resume and audio_play are not readable, so they shouldn't really matter as long as the internal implementation still behaves correctly (assuming audio_play is independent from the audio_playing flag in the status register, that one shouldn't be cleared in this instance).  At least, that's my understanding.  I'll ping byuu and see if he has any input.

**Comment by devinacker** [comment] 2016-10-21 01:19
> audio_busy should be set during the period of time when you're determining whether or not the track exists, then cleared once the track_missing flag is definitively set or cleared

This doesn't currently seem to be the case in higan.

> audio_resume and audio_play are not readable

Both bsnes-plus and higan shift them into the value read from $2000, and the same play flag (i.e. the one bsnes-plus clears on writing $2005) is the one both versions use to determine whether or not audio is supposed to be playing.

**Comment by qwertymodo** [comment] 2016-10-21 01:38
Ok, well I can say for certain that writing to $2005 should not stop playback, and so it should not clear the flag indicating that audio is currently playing. As far as audio_busy, that's fair enough for emulation as long as you can guarantee that if I write to $2005 and immediately read from $2000 that the track_missing flag will be accurate, or that if I write to $2005 and then immediately write to $2007 it will play the correct track (i.e. you guarantee it never *is* busy).  audio_resume, however, really shouldn't be cleared, unless it is latched somewhere else, since it needs to take effect when you start the next track (really it should be cleared by a write to $2007, not $2005).

**Comment by devinacker** [comment] 2016-10-21 01:53
Sorry, I meant to say audio_repeat, not audio_resume (which is indeed only handled when writing $2007). 

I'm changing $2005 to leave the play and repeat flags alone, since that's also how I thought it was supposed to behave.

**Comment by qwertymodo** [comment] 2016-10-21 01:56
I just tried it, and the resume still isn't working.  I confirmed that resume is working on this ROM in higan.

**Comment by devinacker** [comment] 2016-10-21 01:59
What ROM are you using?

**Comment by qwertymodo** [comment] 2016-10-21 02:07
My own Chrono Trigger hack I'm developing right now.

[chrono_msu.zip](https://github.com/devinacker/bsnes-plus/files/543367/chrono_msu.zip)

**Comment by devinacker** [comment] 2016-10-21 05:23
Try it with the latest commit 3d7b4e3. Previously the file wasn't actually seeking to the correct position when resuming playback.

**Comment by mrehkopf** [comment] 2016-10-21 07:31
> writing to $2005 should not stop playback
Wait, what? I wonder how that makes sense in the light of the busy flag... it's meant to give hardware time to prepare the file so it would be unrealistic to assume that it can keep playing the other file simultaneously.
sd2snes must and will stop playback on $2005 write to close the PCM file, open the next, fill the buffer, and clear the busy flag.

**Comment by qwertymodo** [comment] 2016-10-21 07:36
Maybe I'm misunderstanding something, then. It was my understanding that writing to the track registers had no affect on playback until writing to $2007, and only updated the audio_busy and track_missing flags.

**Comment by mrehkopf** [comment] 2016-10-21 08:12
I think that particular bit was left unspecified :/ The discussion about it is probably lost, IIRC byuu axed his message board at some point. Oh, I see he just did it again, it's completely empty.

**Comment by mrehkopf** [comment] 2016-10-21 11:44
Checked back with byuu and in fact playback is stopped upon $2005 write but the play/repeat read flags are not touched. ^^;

**Comment by devinacker** [comment] 2016-10-21 13:09
Looking at higan again, writing $2005 should obviously affect playback by closing the previous audio file, but then it looks like it will continue playing the new selected file once it's actually available, unless I'm missing something. It shouldn't just completely stop the audio indefinitely, right?

Anyway, @qwertymodo did that previous commit fix the resume issue? (I pushed it in a bit of a hurry and I still don't have any actual audio to test with at the moment)

**Comment by qwertymodo** [comment] 2016-10-21 14:58
Didn't get a chance to test last night. Once I get my build machine back up and running I'll let you know.

**Comment by devinacker** [comment] 2016-10-21 20:03
Cool. I'm going to close this since I think $2005 and $2007 now both work consistantly with higan.

Will be examining #54 soon.

**Closed by devinacker** 2016-10-21 20:03 UTC
Labels: msu1

**Comment by devinacker** [comment] 2016-10-24 23:39
Ok, after some more discussion with byuu and the others on this issue, it was determined that clearing the flags (and continuing to play) was a regression in higan v95 which has been reverted in 6dfebcc88669eac9d66e6725111db0a02188e8c2.
