### ISSUE TITLE
Compiling with clang at -O0 causes crash after a few cycles of emulation

### ISSUE THREAD

**Issue by Optiroc** [devinacker/bsnes-plus#15] opened 2015-05-05 07:27 UTC
Which is weird. It seemed like libco was the culprit, and when pulling in the version from bsnes-mercury (https://github.com/libretro/bsnes-mercury) everything seems to work perfect... So with that in place you can use lldb for debugging and tinkering. Are you interested in a pull request with those changes?

**Comment by devinacker** [comment] 2015-05-05 13:50
The version of libco that bsnes-plus uses is an upstream change from bsnes-classic (https://code.google.com/p/bsnes-classic); can you build that fork with -O0 too and see if the same thing happens?

I've built with gcc -O0 on Windows for debugging purposes without issue before, but I don't remember if I had ever done so after the most recent libco changes and I won't be able to try again until I get home from work.

(cc @awjackson)

**Comment by awjackson** [comment] 2015-05-05 19:31
The problem is specific to clang; I've verified that compiling with gcc using -O0 works correctly for both 32-bit and 64-bit builds. I've committed a fix that forces byuu's original version of libco to be used in the specific case of compiling with clang with -O0.

The combination of -O0 and __attribute__((naked)) seems to expose a bug in clang. It doesn't just ignore the __attribute__((naked)) (which would also break co_switch() but would at least be understandable); instead, it generates a nonsensical function prologue that cannot possibly work even for a function without the unusual requirements co_switch() has.

On gcc you can use an attribute to force the co_switch() function to be compiled with optimization settings that allow it to work, but on clang there seems to be no way to turn optimization *on* per-function; you can only turn it *off*.

bsnes-mercury uses raw inline assembly rather than wrapping it in a C function, which makes it immune to compiler misbehaviour but requires platform-specific knowledge of calling conventions and name mangling... that's why they only enable the inline asm on 64-bit Linux and OS X.

**Comment by devinacker** [comment] 2015-05-05 23:59
merged in c1b13d1dfe9ca4a112ce45102d19e4e9c946484b

**Closed by devinacker** 2015-05-05 23:59 UTC
